apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${COMPONENT_NAME}
  description: ${COMPONENT_DESCRIPTION}
  tags:
    - ${TAG_1}
    - ${TAG_2}
  annotations:
    backstage.io/techdocs-ref: dir:.
    ${ANNOTATION_KEY}: ${ANNOTATION_VALUE}
spec:
  type: ${COMPONENT_TYPE}
  lifecycle: ${LIFECYCLE}
  owner: ${OWNER_TEAM}
  providesApis:
    - ${API_NAME}
  dependsOn:
    - resource:${DATABASE_NAME}
    - component:${DEPENDENCY_SERVICE}
  ${ADDITIONAL_SPEC}
